services:
  mysqldb:
    container_name: mysqldb
    image: "mysql:8.0"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: warehouse
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user
    volumes:
      - data:/var/lib/mysql

  app:
    container_name: app
    image: "warehouse:latest"
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/warehouse?allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "user"
      SPRING_DATASOURCE_PASSWORD: "user"

volumes:
  data:
